### PR TITLE
[PR] The proj files have been updated to enable SourceLink

### PR DESCRIPTION
**Pull request by JTOne123**
CSProj files have been updated to enable SourceLink in your nuget
---

*[This pull request was created with an automated workflow]*

I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.

**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)

You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

If you are interesting about this automated workflow and how it works  
https://github.com/JTOne123/GitHubMassUpdater

*If you notice any flaws, please comment and I will try to make fixes manually*

### CODE REVIEW

**Comment by SimonCropp** [comment]
this project does not produce a package. why would sourcelink be required?

**Comment by JTOne123** [comment]
https://www.nuget.org/packages/TextCopy/

it is not required, it is just nice to have
I hope it will increase good debug experience of your nuget

if you disagree, just close

**Comment by SimonCropp** [comment]
i do think sourcelinking is valuable. but the specific project you have updated in this PR is used for [in-solution-weaving](https://github.com/Fody/Home/blob/master/pages/in-solution-weaving.md), so it doesnt produce a nuget and is never run outside this solution

**Comment by JTOne123** [comment]
ok, I see, than sorry)

**Pull request closed without merging**
